authapp/urls.py
from django.urls import path
# from authapp.views import login, register, logout, profile
from authapp.views import UserLoginView, UserRegisterView, logout, profile
# from authapp.views import UserLoginView, register, logout, profile

app_name = 'authapp'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    # path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
]

basketapp/urls.py
from django.urls import path

from basketapp.views import basket_add, basket_delete, basket_edit

app_name = 'basketapp'

urlpatterns = [
    path('basket-add/<int:product_id>/', basket_add, name='basket_add'),
    path('basket-delete/<int:id>/', basket_delete, name='basket_delete'),
    path('edit/<int:id>/<int:quantity>/', basket_edit, name='basket_edit'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),

    # path('products/', products, name='products'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

basketapp/models.py
from django.db import models
from mainapp.models import Product
from authapp.models import User

# Create your models here.


class Basket(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    product = models.ForeignKey(Product, on_delete=models.CASCADE)
    quantity = models.PositiveIntegerField(default=0)
    created_timestamp = models.DateTimeField(auto_now_add=True)

    def __str__(self):
        return f'Корзина для {self.user.username} | Продукт {self.product.name}'

    def sum(self):
        return self.quantity * self.product.price

    def total_quantity(self):
        return sum(i.quantity for i in Basket.objects.filter(user=self.user))

    def total_sum(self):
        return sum(i.sum() for i in Basket.objects.filter(user=self.user))

basketapp/views.py
from django.shortcuts import HttpResponseRedirect
from django.http import JsonResponse
from django.template.loader import render_to_string
from django.contrib.auth.decorators import login_required

from mainapp.models import Product
from basketapp.models import Basket

# Create your views here.


@login_required
def basket_add(request, product_id=None):
    product = Product.objects.get(id=product_id)
    baskets = Basket.objects.filter(user=request.user, product=product)

    if not baskets.exists():
        basket = Basket(user=request.user, product=product)
        basket.quantity = 1
        # basket.save()
        # return HttpResponseRedirect(request.META.get('HTTP_REFERER'))
    else:
        basket = baskets.first()
        basket.quantity += 1
    basket.save()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_delete(request, id=None):
    basket = Basket.objects.get(id=id)
    basket.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))


@login_required
def basket_edit(request, id, quantity):
    if request.is_ajax():
        quantity = int(quantity)
        basket = Basket.objects.get(id=id)
        if quantity > 0:
            basket.quantity = quantity
            basket.save()
        else:
            basket.delete()
        baskets = Basket.objects.filter(user=request.user)
        context = {'baskets': baskets}
        result = render_to_string('basketapp/basket.html', context)
        jr = JsonResponse({'result': result})
        print(jr)
        return jr 

basketapp/templates/basketapp/basket.html
<div class="basket_list">
    {% if baskets %}
        <h4 class="mt-3 mb-3 d-flex justify-content-between align-items-center mb-3">
            Корзина <span class="badge badge-secondary badge-pill">{{ baskets.0.total_quantity }}</span>
        </h4>
        {% for i in baskets %}
            <div class="card mb-3">
                <div class="card-body">
                    <h5 class="card-title">{{ i.product.name }}</h5>
                    <p class="card-text">{{ i.product.short_description }}</p>
                </div>
                <ul class="list-group list-group-flush">
                    <li class="list-group-item bg-light">
                        <div class="row text-center">
                            <div class="col-lg-4">
                                <input name="{{ i.id }}" type="number" class="form-control"
                                       value="{{ i.quantity }}" min="0">
                            </div>
                            <div class="col-lg-4">{{ i.sum }} руб.</div>
                            <div class="col-lg-4">
                                <a href="{% url 'baskets:basket_delete' i.id %}">
                                    <i class="fas fa-trash"></i>
                                </a>
                            </div>
                        </div>
                    </li>
                </ul>
            </div>
        {% endfor %}
        <div class="card mb-3">
            <div class="card-footer">
                <p class="float-left">Итого</p>
                <h4 class="float-right">{{ baskets.0.total_sum }} руб.</h4>
            </div>
        </div>
        <button type="button" class="btn btn-success btn-lg float-right">Оформить</button>
    {% else %}
        <h4 class="mt-3 mb-3 text-center">Корзина пуста</h4>
    {% endif %}
</div>