authapp/urls.py
from django.urls import path
# from authapp.views import login, register, logout, profile
from authapp.views import UserLoginView, UserRegisterView, logout, profile
# from authapp.views import UserLoginView, register, logout, profile

app_name = 'authapp'

urlpatterns = [
    path('login/', UserLoginView.as_view(), name='login'),
    path('register/', UserRegisterView.as_view(), name='register'),
    # path('register/', register, name='register'),
    path('logout/', logout, name='logout'),
    path('profile/', profile, name='profile'),
]

geekshop/urls.py
from django.contrib import admin
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static

from mainapp.views import index

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', index, name='index'),
    path('products/', include('mainapp.urls', namespace='products')),
    path('auth/', include('authapp.urls', namespace='auth')),
    path('baskets/', include('basketapp.urls', namespace='baskets')),
    path('admin-staff/', include('adminapp.urls', namespace='admin_staff')),

    # path('products/', products, name='products'),
]


if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

authapp/models.py
from datetime import timedelta

from django.db import models
from django.contrib.auth.models import AbstractUser
from django.utils.timezone import now


class User(AbstractUser):
    avatar = models.ImageField(upload_to='users_avatar', blank=True)

    activation_key = models.CharField(max_length=128, blank=True)
    activation_key_expires = models.DateTimeField(default=(now() + timedelta(hours=48)))

    def is_activation_key_expired(self):
        return now() > self.activation_key_expires

authapp/forms.py
from hashlib import sha1
from random import random

from django.contrib.auth.forms import AuthenticationForm, UserCreationForm, UserChangeForm
from authapp.models import User
from django.core.exceptions import ValidationError
from django import forms


class UserLoginForm(AuthenticationForm):
    class Meta:
        model = User
        fields = ('username', 'password')

    def __init__(self, *args, **kwargs):
        super(UserLoginForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['username'].label = 'Имя пользователя'
        self.fields['password'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password'].label = 'Пароль'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'


class UserRegisterForm(UserCreationForm):
    class Meta:
        model = User
        fields = ('username', 'email', 'first_name', 'last_name', 'password1', 'password2')

    def __init__(self, *args, **kwargs):
        super(UserRegisterForm, self).__init__(*args, **kwargs)
        self.fields['username'].widget.attrs['placeholder'] = 'Введите имя пользователя'
        self.fields['username'].label = 'Имя пользователя'
        self.fields['email'].widget.attrs['placeholder'] = 'Введите адрес электронной почты'
        self.fields['email'].label = 'Адрес электронной почты'
        self.fields['first_name'].widget.attrs['placeholder'] = 'Введите имя'
        self.fields['first_name'].label = 'Имя'
        self.fields['last_name'].widget.attrs['placeholder'] = 'Введите фамилию'
        self.fields['last_name'].label = 'Фамилия'
        self.fields['password1'].widget.attrs['placeholder'] = 'Введите пароль'
        self.fields['password1'].label = 'Пароль'
        self.fields['password2'].widget.attrs['placeholder'] = 'Подтвердите пароль'
        self.fields['password2'].label = 'Подтверждение пароля'
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'

    def clean_first_name(self):
        name = self.cleaned_data['first_name']
        if len(name) == 0:
            raise ValidationError('Введите ваше имя!')
        return name


class UserProfileForm(UserChangeForm):
    avatar = forms.ImageField(widget=forms.FileInput(), required=False)

    class Meta:
        model = User
        fields = ('first_name', 'last_name', 'avatar', 'username', 'email')

    def __init__(self, *args, **kwargs):
        super(UserProfileForm, self).__init__(*args, **kwargs)
        for field_name, field in self.fields.items():
            field.widget.attrs['class'] = 'form-control py-4'
        self.fields['username'].widget.attrs['readonly'] = True
        self.fields['email'].widget.attrs['readonly'] = True
        self.fields['avatar'].widget.attrs['class'] = 'custom-file-input'

    def clean_first_name(self):
        name = self.cleaned_data['first_name']
        if len(name) == 0:
            # для проверки работоспособности
            print('Не задано имя')
            raise ValidationError('Введите ваше имя!')
        return name

    def save(self):
        user = super(UserProfileForm).save()
        user.is_active = False
        salt = sha1(str(random()).encode('utf8')).hexdigest()[:6]
        user.activation_key = sha1((user.email + salt).encode('utf8')).hexdigest()
        user.save()

authapp/views.py
from django.shortcuts import render, HttpResponseRedirect
from django.contrib import auth
from django.urls import reverse, reverse_lazy
from django.contrib import messages
from django.contrib.auth.decorators import login_required
from django.contrib.auth.views import LoginView
from django.views.generic.edit import CreateView, UpdateView
from django.contrib.messages.views import SuccessMessageMixin

from authapp.forms import UserLoginForm, UserRegisterForm, UserProfileForm
from basketapp.models import Basket
from authapp.models import User

# Create your views here.

class UserLoginView(LoginView):
    authentication_form = UserLoginForm
    template_name = 'authapp/login.html'
    extra_context = {
        'title': 'GeekShop - Авторизация',
        'form_class': 'col-lg-5',
        'header': 'Авторизация',
    }
    success_url = reverse_lazy('index')


# def login(request):
#     if request.method == 'POST':
#         form = UserLoginForm(data=request.POST)
#         if form.is_valid():
#             username = request.POST['username']
#             password = request.POST['password']
#             user = auth.authenticate(username=username, password=password)
#             if user and user.is_active:
#                 auth.login(request, user)
#                 return HttpResponseRedirect(reverse('index'))
#     else:
#         form = UserLoginForm()
#     context = {
#         'form': form,
#         'title': 'GeekShop - Авторизация',
#         'form_class': 'col-lg-5',
#         'header': 'Авторизация',
#     }
#     return render(request, 'authapp/login.html', context)


class UserRegisterView(SuccessMessageMixin, CreateView):
    model = User
    template_name = 'authapp/register.html'
    form_class = UserRegisterForm
    extra_context = {
        'title': 'GeekShop - Регистрация',
        'form_class': 'col-lg-7',
        'header': 'Создать аккаунт',
    }
    success_url = reverse_lazy('auth:login')
    success_message = 'Регистрация успешна!'
    


# def register(request):
#     if request.method == 'POST':
#         form = UserRegisterForm(data=request.POST)
#         if form.is_valid():
#             form.save()
#             messages.success(request, 'Регистрация успешна!')
#             return HttpResponseRedirect(reverse('auth:login'))
#     else:
#         form = UserRegisterForm()
#     context = {
#         'form': form,
#         'title': 'GeekShop - Регистрация',
#         'form_class': 'col-lg-7',
#         'header': 'Создать аккаунт',
#     }
#     return render(request, 'authapp/register.html', context)


def logout(request):
    auth.logout(request)
    return HttpResponseRedirect(reverse('index'))


# class UserProfileView(UpdateView):
#     model = User
#     template_name = 'authapp/profile.html'
#     form_class = UserProfileForm
#
#     context = {
#         'title': 'GeekShop - Профиль',
#         'baskets': Basket.objects.filter(user=request.user),
#     }



@login_required
def profile(request):
    if request.method == 'POST':
        form = UserProfileForm(data=request.POST, instance=request.user, files=request.FILES)
        if form.is_valid():
            form.save()
            messages.success(request, 'Изменения сохранены')
            return HttpResponseRedirect(reverse('auth:profile'))
    else:
        form = UserProfileForm(instance=request.user)
    context = {
        'form': form,
        'title': 'GeekShop - Профиль',
        'baskets': Basket.objects.filter(user=request.user),
    }
    return render(request, 'authapp/profile.html', context)

authapp/templates/authapp/base.html
{% load staticfiles %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="utf-8"/>
    <meta http-equiv="X-UA-Compatible" content="IE=edge"/>
    <meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no"/>
    <meta name="description" content=""/>
    <meta name="author" content=""/>
    <title>{{ title }}</title>
    <link href="{% static 'css/auth-admin.css' %}" rel="stylesheet"/>
    <script src="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/5.15.1/js/all.min.js"
            crossorigin="anonymous"></script>
</head>
<body class="bg-primary">
<div id="layoutAuthentication">
    <div id="layoutAuthentication_content">
        <main>
            <div class="container">
                <div class="row justify-content-center">
                    <div class="{{ form_class }}">
                        {% block errors %}
                        {% endblock %}
                        <div class="card shadow-lg border-0 rounded-lg mt-5">
                            <div class="card-header"><h3 class="text-center font-weight-light my-4">{{ header }}</h3>
                            </div>
                            <div class="card-body">
                                {% block form %}
                                {% endblock %}
                            </div>
                            <div class="card-footer text-center">
                                {% block footer %}
                                {% endblock %}
                            </div>
                        </div>
                    </div>
                </div>
            </div>
        </main>
    </div>
</div>
<script src="https://code.jquery.com/jquery-3.5.1.slim.min.js" crossorigin="anonymous"></script>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@4.5.3/dist/js/bootstrap.bundle.min.js"
        crossorigin="anonymous"></script>
<script src="{% static 'js/auth-admin.js' %}"></script>
</body>
</html>

authapp/templates/authapp/login.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block errors %}
    {% if form.non_field_errors or messages %}
        <div class="alert
        {% if messages %} alert-success {% else %} alert-danger {% endif %}
        alert-dismissible fade show" role="alert"
             style="margin-top: 50px;">
            {% if messages %}
                {% for i in messages %}
                    {{ i }}
                {% endfor %}
            {% else %}
                {% for i in form.non_field_errors %}
                    {{ i }}
                {% endfor %}
            {% endif %}
            {# <strong>Holy guacamole!</strong> You should check in on some of those fields below.#}
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
{% endblock %}

{% block form %}
    <form action="{% url 'auth:login' %}" method="post">
        {% csrf_token %}
        {% for i in form %}
            <div class="form-group">
                <label class="small mb-1" for="{{ i.id_for_label }}">{{ i.label }}</label>
                {{ i }}
            </div>
        {% endfor %}

        <div class="form-group d-flex align-items-center justify-content-between mt-4 mb-0">
            <a class="small" href="#">Забыли пароль?</a>
            <input class="btn btn-primary" type="submit" value="Авторизоваться">
        </div>
    </form>
{% endblock %}

{% block footer %}
    <div class="small"><a href="{% url 'auth:register' %}">Нужен аккаунт? Зарегистрируйся!</a></div>
{% endblock %}

authapp/templates/authapp/profile.html
{% extends 'mainapp/base.html' %}
{% load staticfiles %}

{% block css %}
    <link href="{% static 'css/profile.css' %}" rel="stylesheet">
{% endblock %}

{% block content %}
    <div class="container">
    <div class="row">
        <div class="col-lg-7">
            <h4 class="mt-3 mb-3">Профиль</h4>
            {% block errors %}
                {% if form.errors or messages %}
                    <div class="alert
                        {% if messages %} alert-success {% else %} alert-danger {% endif %}
                        alert-dismissible fade show" role="alert"
                         style="margin-top: 50px;">
                        {% if messages %}
                            {% for i in messages %}
                                {{ i }}
                            {% endfor %}
                        {% else %}
                            {{ form.errors }}
                        {% endif %}
                        <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                            <span aria-hidden="true">&times;</span>
                        </button>
                    </div>
                {% endif %}
            {% endblock %}
            <div class="col-lg-12 text-center">
                <img width="100" height="100"
                     src="{% if user.avatar %} {{ user.avatar.url }} {% else %} {% static 'vendor/img/users/def_avatar.webp' %} {% endif %}"
                     class="img-thumbnail">
            </div>
            <form action="{% url 'auth:profile' %}" method="post" enctype="multipart/form-data">
                {% csrf_token %}
                <div class="form-row">
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.first_name.id_for_label }}">Имя</label>
                            {{ form.first_name }}
                        </div>
                    </div>
                    <div class="col-lg-6">
                        <div class="form-group">
                            <label class="small mb-1" for="{{ form.last_name.id_for_label }}">Фамилия</label>
                            {{ form.last_name }}
                        </div>
                    </div>
                </div>
                <div class="form-row mb-2">
                    <div class="col-lg-12">
                        <div class="custom-file">
                            {{ form.avatar }}
                            <label class="custom-file-label" for="{{ form.avatar.id_for_label }}">
                                Выберите изображение
                            </label>
                        </div>
                    </div>
                </div>
                <div class="form-row">
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.username.id_for_label }}">Имя пользователя</label>
                        {{ form.username }}
                    </div>
                    <div class="col-lg-6">
                        <label class="small mb-1" for="{{ form.email.id_for_label }}">Адрес электронной
                            почты</label>
                        {{ form.email }}
                    </div>
                </div>
                <div class="form-row">
{#                    <div class="col-lg-6">#}
{#                        <label class="small mb-1" for="inputBirthday">День рождения</label>#}
{#                        <input class="form-control py-4" id="inputBirthday" type="date"#}
{#                               aria-describedby="birthdayHelp" value="1998-01-13"/>#}
{#                    </div>#}
                    <div class="col-lg-12" style="margin-top: 33px;">
                        <input class="btn btn-info btn-block" type="submit" value="Сохранить">
                    </div>
                </div>
            </form>
        </div>
        <div class="col-lg-5">
            {% include 'basketapp/basket.html' %}
        </div>
    </div>
</div>
{% endblock %}

authapp/templates/authapp/register.html
{% extends 'authapp/base.html' %}
{% load staticfiles %}

{% block errors %}
    {% if form.errors %}
        <div class="alert alert-warning alert-dismissible fade show" role="alert"
             style="margin-top: 50px;">
            {{ form.errors }}
             <strong>Holy guacamole!</strong> You should check in on some of those fields below.
            <button type="button" class="close" data-dismiss="alert" aria-label="Close">
                <span aria-hidden="true">&times;</span>
            </button>
        </div>
    {% endif %}
{% endblock %}

{% block form %}
    <form action="{% url 'auth:register' %}" method="post">
        {% csrf_token %}
        <div class="form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1"
                           for="{{ form.first_name.id_for_label }}">{{ form.first_name.label }}</label>
                    {{ form.first_name }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1"
                           for="{{ form.last_name.id_for_label }}">{{ form.last_name.label }}</label>
                    {{ form.last_name }}
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1"
                           for="{{ form.username.id_for_label }}">{{ form.username.label}}</label>
                    {{ form.username }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1"
                           for="{{ form.email.id_for_label }}">{{ form.email.label }}</label>
                    {{ form.email }}
                </div>
            </div>
        </div>
        <div class="form-row">
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1"
                           for="{{ form.password1.id_for_label }}">{{ form.password1.label }}</label>
                    {{ form.password1 }}
                </div>
            </div>
            <div class="col-md-6">
                <div class="form-group">
                    <label class="small mb-1"
                           for="{{ form.password2.id_for_label }}">{{ form.password2.label }}</label>
                    {{ form.password2 }}
                </div>
            </div>
        </div>
        <div class="form-group mt-4 mb-0">
            <input class="btn btn-primary btn-block" type="submit" value="Создать аккаунт">
        </div>
    </form>
{% endblock %}

{% block footer %}
    <div class="small"><a href="{% url 'auth:login' %}">Уже есть аккаунт? Авторизоваться</a></div>
{% endblock %}